name: Frontend CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
    
    - name: Create Production .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env.production

    - name: Install dependencies
      run: npm ci

    # - name: Run linting
    #   run: npm run lint
    #   continue-on-error: true

    # - name: Run tests
    #   run: npm test
    #   continue-on-error: true

    - name: Build
      run: npm run build
    
    - name: 'Authenticate to Google Cloud'
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up Google Cloud SDK
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Upload to Cloud Storage
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
      run: |
        echo "Deploying to ${{ secrets.FRONTEND_BUCKET_NAME }}"
        gsutil -m rsync -d -r dist gs://${{ secrets.FRONTEND_BUCKET_NAME }}/
        gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://${{ secrets.FRONTEND_BUCKET_NAME }}/**/*.html
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://${{ secrets.FRONTEND_BUCKET_NAME }}/**/*.{js,css,png,jpg,jpeg,gif,svg,woff,woff2}
        echo "Frontend deployment complete"
